# Generated by Django 3.0.3 on 2020-05-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_of_branch',
            field=models.CharField(default='', max_length=128, verbose_name='所在部门编号'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('1', '在职'), ('2', '兼职'), ('3', '试用'), ('4', '离职'), ('5', '返聘'), ('6', '退休')], default='在职', max_length=32, verbose_name='员工状态'),
        ),
    ]
