# Generated by Django 3.0.3 on 2020-05-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200520_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'personnel'), (1, 'Admin')], default=0, verbose_name='用户类型'),
        ),
    ]
