# Generated by Django 3.0.3 on 2020-05-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_auto_20200521_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False, verbose_name='部门编号')),
                ('name', models.CharField(max_length=128, verbose_name='部门名称')),
                ('work_id', models.CharField(max_length=128, verbose_name='部门职能编号')),
                ('pre_dep_id', models.CharField(max_length=128, verbose_name='上级部门编号')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=8, verbose_name='性别')),
                ('nation', models.CharField(max_length=128, verbose_name='民族')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('politics', models.CharField(max_length=128, verbose_name='政治面貌')),
                ('education', models.CharField(max_length=128, verbose_name='文化程度')),
                ('marriage', models.CharField(max_length=128, verbose_name='婚姻状况')),
                ('hometown', models.CharField(max_length=128, verbose_name='籍贯')),
                ('id_card', models.CharField(max_length=128, verbose_name='身份证')),
                ('phone', models.CharField(max_length=12, verbose_name='电话号码')),
                ('place', models.CharField(max_length=12, verbose_name='档案存放地')),
                ('home_card', models.CharField(max_length=128, verbose_name='户口所在地')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('num', models.CharField(max_length=128, verbose_name='工作证号')),
                ('in_time', models.DateField(verbose_name='入职日期')),
                ('pos', models.CharField(max_length=128, verbose_name='工作岗位')),
                ('duty', models.CharField(max_length=128, verbose_name='职务')),
                ('pre_num', models.CharField(max_length=128, verbose_name='上级员工编号')),
                ('status', models.IntegerField(choices=[(1, '在职'), (2, '兼职'), (3, '试用'), (4, '离职'), (5, '返聘'), (6, '退休')], default=1, verbose_name='员工状态')),
                ('account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='login.User')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.department')),
            ],
            options={
                'verbose_name': '职工',
                'verbose_name_plural': '职工',
                'ordering': ['c_time'],
            },
        ),
    ]
