# Generated by Django 3.0.3 on 2020-05-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200521_1708'),
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='emp\\img\\default.jpg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='account',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.department', verbose_name='所属部门编号'),
        ),
    ]
