# Generated by Django 3.0.3 on 2020-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20200525_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='img\\default.jpg', upload_to='img', verbose_name='照片'),
        ),
    ]
